---
- name: Create jenkins slave user
  user:
    name: "{{ jenkins_slave_username }}"
    password: >-
      {{ jenkins_slave_password
          | password_hash('sha512', 65535 | random(seed=inventory_hostname)
          | string) }}
    update_password: always
    createhome: true
    shell: /bin/bash
    state: present
  become: true

- name: Create jenkins slave home directory
  file:
    path: "{{ jenkins_slave_home }}"
    state: directory
    owner: "{{ jenkins_slave_username }}"
    group: "{{ jenkins_slave_username }}"
    mode: "0755"
  become: true
  when: jenkins_slave_home | trim

- import_tasks: service.yml