---
- name: Install requirements
  apt:
    name: "{{ requirements }}"
    update_cache: yes
    state: present
  retries: 3
  delay: 2
  register: result
  until: result is success
  become: true
  when: requirements | default([]) | length > 0

- name: Create jenkins user
  user:
    name: "{{ jenkins_slave_linux_jenkins_username }}"
    password: >-
      {{ jenkins_slave_linux_jenkins_password
          | password_hash('sha512', 65535 | random(seed=inventory_hostname)
          | string) }}
    update_password: always
    state: present
    createhome: true
    shell: /bin/bash
  become: true

- name: Set authorized key
  authorized_key:
    user: "{{ jenkins_slave_linux_jenkins_username }}"
    state: present
    key: "{{ jenkins_slave_linux_jenkins_public_key }}"
  become: true
  when: jenkins_slave_linux_jenkins_public_key | trim

- name: Create jenkins slave home directory
  file:
    path: "{{ jenkins_slave_linux_home }}"
    state: directory
    owner: "{{ jenkins_slave_linux_jenkins_username }}"
    group: "{{ jenkins_slave_linux_jenkins_username }}"
    mode: "0755"
  become: true
  when: jenkins_slave_linux_home | trim
