---
- name: Create jenkins slave user
  win_user:
    name: "{{ jenkins_slave_username }}"
    password: "{{ jenkins_slave_password }}"
    update_password: always
    state: present

- name: Create jenkins slave home directory
  win_file:
    path: "{{ jenkins_slave_home }}"
    state: directory

- import_tasks: service.yml
