---
- name: Download agent.jar from jenkins master
  win_get_url:
    url: "{{ jenkins_master_url }}/jnlpJars/agent.jar"
    dest: "{{ jenkins_slave_home }}/agent.jar"
    force: true

- name: Get jnlp content of the jenkins slave
  win_uri:
    url: "{{ jenkins_master_url }}/computer/{{ jenkins_slave_node_name }}/slave-agent.jnlp"
    method: GET
    force_basic_auth: true
    user: "{{ jenkins_master_username }}"
    password: "{{ jenkins_master_password_or_token }}"
    return_content: true
  register: jenkins_slave_jnlp_file

- name: Extract node secret from the jnlp content
  set_fact:
    jenkins_slave_node_secret: "{{ jenkins_slave_jnlp_file.content | regex_search('([a-z0-9]*)(?=</argument>)') }}"

- name: Get JAVA_HOME environment variable
  win_shell: |
    [System.Environment]::GetEnvironmentVariable("JAVA_HOME","Machine")
  register: java_home_env
  changed_when: false

- name: Copy jenkins slave service file
  win_template:
    src: jenkins-slave.cmd.j2
    dest: "{{ jenkins_slave_home }}/jenkins-slave.cmd"
  vars:
    java_home: "{{ java_home_env.stdout | trim }}"
  register: jenkins_slave_service_file

- name: Install nssm
  win_chocolatey:
    name: nssm
    state: present

- name: Create jenkins slave service via nssm
  win_nssm:
    name: jenkins-slave
    application: "{{ jenkins_slave_home }}/jenkins-slave.cmd"
    state: present

# This is required to be set for non-service accounts that need to run as a service
- name: Grant jenkins account the SeServiceLogonRight user right
  win_user_right:
    name: SeServiceLogonRight
    users:
      - "{{ jenkins_slave_username }}"
    action: add

- name: Restart jenkins slave service
  win_service:
    name: jenkins-slave
    state: restarted
    username: "{{ jenkins_slave_username }}"
    password: "{{ jenkins_slave_password }}"
  when: jenkins_slave_service_file.changed

- name: Ensure jenkins slave service is started
  win_service:
    name: jenkins-slave
    state: started
    username: "{{ jenkins_slave_username }}"
    password: "{{ jenkins_slave_password }}"
