---
- name: Get java home path from env
  win_shell: '[System.Environment]::GetEnvironmentVariable("JAVA_HOME","Machine")'
  register: java_home_env
  changed_when: false

- name: Copy jenkins agent service file
  win_template:
    src: service.cmd.j2
    dest: "{{ slave_windows_remotefs }}/service.cmd"
  vars:
    java_home: "{{ java_home_env.stdout | trim }}"
  notify: Retart the jenkins agent service

- name: Install nssm
  win_chocolatey:
    name: nssm
    state: present

- name: Create the jenkins agent service via nssm
  win_nssm:
    name: "{{ slave_windows_service_name }}"
    application: "{{ slave_windows_remotefs }}/service.cmd"
    state: present

# This is required to be set for non-service accounts that need to run as a service
- name: Grant jenkins account the SeServiceLogonRight user right
  win_user_right:
    name: SeServiceLogonRight
    users:
      - "{{ slave_windows_jenkins_username }}"
    action: add

- name: Start the jenkins agent service
  win_service:
    name: "{{ slave_windows_service_name }}"
    state: started
    username: "{{ slave_windows_jenkins_username }}"
    password: "{{ slave_windows_jenkins_password }}"
